# Generated by Django 3.2.7 on 2021-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Продукт')),
                ('link', models.URLField(help_text='Укажіть інтернет адресу', verbose_name='Інтернет-адреса')),
                ('price', models.IntegerField(help_text='Укажіть ціну', verbose_name='Ціна продукту')),
                ('added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
    ]
