# Generated by Django 3.2.7 on 2021-10-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_wishlistuser_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistuser',
            options={'verbose_name': 'wishlistuser', 'verbose_name_plural': 'wishlistusers'},
        ),
        migrations.AlterField(
            model_name='wishlistuser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
